// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj8q1hP7hEahYIlvtzGf9ayKZc6NXGqVA',
    appId: '1:272064396450:web:c19bb3f684b1031a8e6bfb',
    messagingSenderId: '272064396450',
    projectId: 'nearme-e2b6f',
    authDomain: 'nearme-e2b6f.firebaseapp.com',
    databaseURL: 'https://nearme-e2b6f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nearme-e2b6f.appspot.com',
    measurementId: 'G-VTD4QKN0Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4gTfDaamRNI6P0GsOgsjzrcC4z5V7qmE',
    appId: '1:272064396450:android:a7d85bb41d8b20728e6bfb',
    messagingSenderId: '272064396450',
    projectId: 'nearme-e2b6f',
    databaseURL: 'https://nearme-e2b6f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nearme-e2b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc3F-ULkSb8aq37J1JJygP-djdieYvh8k',
    appId: '1:272064396450:ios:26f9fe4a4ff423118e6bfb',
    messagingSenderId: '272064396450',
    projectId: 'nearme-e2b6f',
    databaseURL: 'https://nearme-e2b6f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nearme-e2b6f.appspot.com',
    iosClientId: '272064396450-hudh3e5mvqe4ltkdgi7arb55f0k1ut9b.apps.googleusercontent.com',
    iosBundleId: 'me.lpka.nearMeClient',
  );
}
